# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: shifa-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   gcePersistentDisk:
#     pdName: shifa-pv-disk
#     fsType: ext4

#   hostPath:
#     path: "/shifa_PV_dir"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: shifa-pvc
# spec:
#   volumeName: shifa-pv
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: standard
#   selector:
#     matchLabels:
#       name: shifa-pv

apiVersion: v1
kind: PersistentVolume
metadata:
  name: shifa-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    # pdName: shifa-pv-disk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shifa-pvc
spec:
  volumeName: shifa-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      name: shifa-pv
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/kube-429214/my-k8-repo/container2
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        volumeMounts:
        - mountPath: /app/shifa_PV_dir
          name: shifa-storage
      volumes:
      - name: shifa-storage
        persistentVolumeClaim:
          claimName: shifa-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service2
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001


